{% set version = "2023.5.0" %}
package:
  name: intake-dynamodb
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/i/intake-dynamodb/intake-dynamodb-{{ version }}.tar.gz
  sha256: 9d6bd78a007ec2026d99c79d2d803b39a6d3d074ee6a5ee1b2c4c4b144866836

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - dask
    - intake
    - s3fs

test:
  imports:
    - intake_dynamodb
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/intake-dynamodb/intake-dynamodb
  summary: Intake plugin for reading from AWS Dynamodb
  license_file: LICENSE
  license: BSD-2-Clause

extra:
  recipe-maintainers:
    - raybellwaves
