{% set version = "2023.4.1" %}
package:
  name: intake-dynamodb
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/intake-dynamodb/intake-dynamodb-{{ version }}.tar.gz
  sha256: f0d9905ed78f84cc9cea79358042b690deeccdc85ceaf016a31b27556979164f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - dask
    - intake
    - s3fs

test:
  imports:
    - intake_dynamodb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/intake-dynamodb/intake-dynamodb
  summary: Intake plugin for reading from AWS Dynamodb
  license_file: LICENSE
  license: BSD-2-Clause

extra:
  recipe-maintainers:
    - raybellwaves
